# Generated by Django 4.0.2 on 2022-02-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('pickup_id', models.CharField(default='', max_length=100)),
                ('drop_id', models.CharField(default='', max_length=100)),
                ('price', models.CharField(default='', max_length=100)),
                ('distance', models.CharField(default='', max_length=100)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
